# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM-CI

on:
  push:
    branches-ignore:
      - master
      
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20 for workflow
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo "Workflow running on Node.js 20"
      
  build:
    needs: setup
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test -- --reporter json --reporter-option output=test-results.json
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-report-${{ matrix.node-version }}
          path: test-results.json
