name: 'Test Report'
on:
  workflow_run:
    workflows: ['NPM-CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results-report-${{ matrix.node-version }}      # artifact name
        name: Mocha Tests-${{ matrix.node-version }}                  # Name of the check run which will be created
        path: '*.json'                     # Path to test results (inside artifact .zip)
        reporter: mocha-json              # Format of test results
